# Generated by Django 5.2.4 on 2025-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0007_screensettings_waiting_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_year',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الولادة'),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('غيباً', 'غيباً'), ('نظراً', 'نظراً')], max_length=10, null=True, verbose_name='غيباً/نظراً'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الأب'),
        ),
        migrations.AddField(
            model_name='student',
            name='institute_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المعهد'),
        ),
        migrations.AddField(
            model_name='student',
            name='memorized_parts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الأجزاء المحفوظة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم والكنية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('in_exam', 'في الامتحان'), ('waiting', 'ينتظر'), ('on_waiting_list', 'قائمة الانتظار')], default='waiting', max_length=20),
        ),
    ]
