# Generated by Django 5.2.4 on 2025-07-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0020_student_subroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subroom',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='عام التولد'),
        ),
    ]
