# Generated by Django 5.2.4 on 2025-08-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0021_remove_student_birth_date_remove_student_subroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('waiting', 'ينتظر'), ('in_exam', 'في السبر'), ('on_waiting_list', 'قائمة الانتظار'), ('finished', 'تم الانتهاء'), ('late', 'متأخر')], default='waiting', max_length=20),
        ),
    ]
