# Generated by Django 5.2.4 on 2025-08-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0022_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.CharField(default='room1', max_length=50),
        ),
    ]
