# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0023_student_subroom_alter_student_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='grade',
            field=models.FloatField(),
        ),
    ]
