# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0024_alter_examresult_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='screensettings',
            name='public_screen_mode',
            field=models.CharField(
                choices=[('rooms', 'عرض اللجان الحالي'), ('window', 'عرض فترة 15 دقيقة')],
                default='rooms',
                max_length=20,
            ),
        ),
    ]
